### ISSUE TITLE
Odom not publishing

### ISSUE THREAD

**Issue by mattlangford** [uf-mil/rawgps-tools#1]
After upgrading the sub computer and pulling the most recent code from rawgps-tools, the sub did not publish odom. I traced this problem to the odom_estimator nodelet. It appears that without GPS, the state never gets initially set. 

The initial state estimate should get set in the `got_imu` callback on [line 181](https://github.com/uf-mil/rawgps-tools/blob/master/odom_estimator/src/nodelet.cpp#L181), but this requires `last_good_dvl` to be set. But, `last_good_dvl` doesn't get set until [line 433](https://github.com/uf-mil/rawgps-tools/blob/master/odom_estimator/src/nodelet.cpp#L433) which is after `if(!state) return;` is executed thereby never allowing `last_good_dvl` to get set which in turn never initiates the state.

I looked on the old sub computer and it was running an older version of the code downloaded from git (not cloned or anything so it never got updated). We went back to an older revision of the odom_estimator code and it's working.

**Comment by forrestv** [comment]
Huh, wow. I'll look into it.
On Jun 12, 2016 7:58 PM, "mattlangford" <notifications@github.com> wrote:

After upgrading the sub computer and pulling the most recent code from
rawgps-tools, the sub did not publish odom. I traced this problem to the
odom_estimator nodelet. It appears that without GPS, the state never gets
initially set.

The initial state estimate should get set in the got_imu callback on line
181
<https://github.com/uf-mil/rawgps-tools/blob/master/odom_estimator/src/nodelet.cpp#L181>,
but this requires last_good_dvl to be set. But, last_good_dvl doesn't get
set until line 433
<https://github.com/uf-mil/rawgps-tools/blob/master/odom_estimator/src/nodelet.cpp#L433>
which is after if(!state) return; is executed thereby never allowing
last_good_dvl to get set which in turn never initiates the state.

I looked on the old sub computer and it was running an older version of the
code downloaded from git (not cloned or anything so it never got updated).
We went back to an older revision of the odom_estimator code and it's
working.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/uf-mil/rawgps-tools/issues/1>, or mute the thread
<https://github.com/notifications/unsubscribe/AADp4HJqMvMjfAlL7zX5BMFaCCiVp5nZks5qLMdCgaJpZM4Iz9hV>
.

**Comment by mattlangford** [comment]
It appears if you move `f(!state) return;` below where it sets `last_good_dvl` it would fix it.
